name: easygold_app_v3
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.13.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  get_it: ^9.3.0
  injectable: ^3.0.0
  shared_preferences: ^2.5.5
  go_router: ^18.0.2
  equatable: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.11.1
  retrofit: ^4.10.0
  logger: ^2.8.0
  freezed: ^4.0.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  envied: ^1.3.10
  json_annotation: ^4.12.0
  json_serializable: ^6.14.1
  easy_localization: ^3.0.8
  easy_localization_loader: ^2.0.2
  aws_common: ^0.7.15
  aws_signature_v4: ^0.6.13
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^3.1.3
  build_runner: ^2.16.1
  retrofit_generator: ^10.2.11
  envied_generator: ^1.3.10
  flutter_gen:

flutter_gen:
  output: lib/generated
  integrations:
    # image: true
    # flutter_svg: true
    # rive: true
    # lottie: true
    # json_serializable: true
flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansLao-Bold.ttf
          weight: 700

